/* 
 * API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = TruckPlanApiClient.Client.SwaggerDateConverter;

namespace TruckPlanApiClient.Model
{
    /// <summary>
    /// Defines ApiResultStatusCode
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum ApiResultStatusCode
    {
        /// <summary>
        /// Enum Success for value: Success
        /// </summary>
        [EnumMember(Value = "Success")]
        Success = 1,
        /// <summary>
        /// Enum ServerError for value: ServerError
        /// </summary>
        [EnumMember(Value = "ServerError")]
        ServerError = 2,
        /// <summary>
        /// Enum BadRequest for value: BadRequest
        /// </summary>
        [EnumMember(Value = "BadRequest")]
        BadRequest = 3,
        /// <summary>
        /// Enum NotFound for value: NotFound
        /// </summary>
        [EnumMember(Value = "NotFound")]
        NotFound = 4,
        /// <summary>
        /// Enum ListEmpty for value: ListEmpty
        /// </summary>
        [EnumMember(Value = "ListEmpty")]
        ListEmpty = 5,
        /// <summary>
        /// Enum LogicError for value: LogicError
        /// </summary>
        [EnumMember(Value = "LogicError")]
        LogicError = 6,
        /// <summary>
        /// Enum UnAuthorized for value: UnAuthorized
        /// </summary>
        [EnumMember(Value = "UnAuthorized")]
        UnAuthorized = 7    }
}
